### ISSUE TITLE
Axes don't match array

### ISSUE THREAD

**Issue by AKASH2907** [AdrianUng/keras-triplet-loss-mnist#3]
Hi @AdrianUng ,

I tried to train it on my own dataset. While loading the model, it shows the following error. 

    model = _deserialize_model(f, custom_objects, compile)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    reshape=False)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/intern_akash/akash_hpc/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

It works perfectly on MNIST dataset.

**Comment by AdrianUng** [comment]
Hello, @AKASH2907 and thank you for your question!

Please tell me more about your training data...
What it is, how many dimensions it has, and the shape of the array used during training.

**Comment by AKASH2907** [comment]
@AdrianUng , My dataset input image shape is 160, 160, 3. Then I'm processing it with imagenet model and generating an embeddings of dimension 512. Rest all of the stuff remains same. I trained for 5 epochs only. Tried to alter ModelCheckpoint and save_model separately. But at the time of loading, it's showing the above error. I used this. 

model = load_model('weights_triplets.h5',
			custom_objects={'triplet_loss_adapted_from_tf':triplet_loss_adapted_from_tf})

Keras version 2.2.4, tensorflow - 1.12.0

**Comment by AdrianUng** [comment]
I'm wondering why it works on MNIST but not on your own data...

How many images are you passing to the model for training?
The shape of your nd.array should be (nr_images, 160,160,3)

Try using a different model, it might have to do with that as well. So define a simple model. When you say Imagenet model, which architecture are you using?

**Comment by AKASH2907** [comment]
Input dimension is (number_of_images, 160, 160, 3), otherwise it should throw the error at the training time. 

I am using XceptionNet. I can check it with simple model.

**Comment by AdrianUng** [comment]
Your error was encountered for a different project and it's actually connected (most likely) to how the GPUs are used: [this issue here](https://github.com/keras-team/keras/issues/9562)

How many GPUs are you using throughout training? I assume it's at least 2.
Please try training your model with just 1 GPU and it should be fine. If not, there are other comments that might help in the thread I mentioned earlier.

**Comment by AdrianUng** [comment]
Try [this workaround](https://github.com/keras-team/keras/issues/9562#issuecomment-431039275) and let me know how it goes...
Best of luck!

**Comment by AKASH2907** [comment]
It's not with the GPUs. It's something related to this bug. I guess:
https://github.com/keras-team/keras/pull/11847

I tried that multi_gpu thing. Unfortunately, it fails. I am still trying. I'll update if weights are loaded properly.

**Comment by AKASH2907** [comment]
Hey @AdrianUng 

I guess the issue is with ModelCheckpoint. I tried saving weights via different experiments. If I saave the model as model.save after training, then there'e no error in loading the weights. I can't figure out why this is happening though.
